name: Scrape Image URLs

on:
  workflow_dispatch:
    inputs:
      sumber:
        description: 'Sumber Gambar'
        required: true
        type: choice
        options: 
          - pixabay
          - google
        default: 'pixabay'
      keyword:
        description: 'Kata Kunci Pencarian'
        required: true
        default: 'nature'
      limit:
        description: 'Jumlah Gambar'
        required: true
        default: '20'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # --- TAMBAHKAN BLOK INI UNTUK MEMBERI IZIN MENULIS ---
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install requests
      
      - name: Run Scraper
        env:
          BOT_LICENSE_EMAIL: ${{ secrets.BOT_LICENSE_EMAIL }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
        run: |
          python dist/scrape_action.py --sumber ${{ github.event.inputs.sumber }} --keyword "${{ github.event.inputs.keyword }}" --limit ${{ github.event.inputs.limit }}
          
      - name: Commit and push image list
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add image_list.txt
          # Hanya commit jika ada perubahan
          if ! git diff --staged --quiet; then
            git commit -m "Update image list for keyword: ${{ github.event.inputs.keyword }}"
            git push
          else
            echo "Tidak ada perubahan pada image_list.txt"
          fi
