name: Bot Auto Tweet - Txt File
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy requests beautifulsoup4
      - name: Run Txt Bot
        # --- PERBAIKAN DI SINI ---
        # Menjalankan skrip langsung dari direktori utama, bukan dari /dist
        run: python dist/bot_txt.py
        env:
          BOT_LICENSE_EMAIL: ${{ secrets.BOT_LICENSE_EMAIL }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
